"""hotels admins table adding

Revision ID: 385bc8268b70
Revises: 609b811b3f85
Create Date: 2026-03-30 05:54:51.176412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '385bc8268b70'
down_revision: Union[str, Sequence[str], None] = '609b811b3f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels_admins',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('bot_hashed_password', sa.LargeBinary(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('row_id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('hotel_id')
    )
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_table('hotels_admins')
    # ### end Alembic commands ###
