"""type bytes for password

Revision ID: 480b79b13ab6
Revises: 65ab5a456295
Create Date: 2026-03-27 19:59:39.321651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480b79b13ab6'
down_revision: Union[str, Sequence[str], None] = '65ab5a456295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 
        'hashed_password',
        existing_type=sa.String(), 
        type_=sa.LargeBinary(),   
        postgresql_using='hashed_password::bytea',
        existing_nullable=False   
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
