"""deleted at adding

Revision ID: 609b811b3f85
Revises: 23f19463e3fe
Create Date: 2026-03-28 19:21:37.963676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609b811b3f85'
down_revision: Union[str, Sequence[str], None] = '23f19463e3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_room_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_user_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.add_column('hotels', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('rooms_hotel_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'hotels', ['hotel_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_hotel_id_fkey'), 'rooms', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('rooms', 'deleted_at')
    op.drop_column('hotels', 'deleted_at')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_user_id_fkey'), 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('bookings_room_id_fkey'), 'bookings', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
