"""email adding

Revision ID: 72682994abe4
Revises: 6af575eff140
Create Date: 2026-03-25 18:04:01.906255

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72682994abe4"
down_revision: Union[str, Sequence[str], None] = "6af575eff140"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("email", sa.String(), nullable=False))
    op.create_unique_constraint(None, "clients", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "clients", type_="unique")
    op.drop_column("clients", "email")
    # ### end Alembic commands ###
