"""make_chat_id_nullable

Revision ID: 95392888d827
Revises: 2edd87060231
Create Date: 2026-03-30 11:56:57.434193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95392888d827'
down_revision: Union[str, Sequence[str], None] = '2edd87060231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels_admins', 'chat_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels_admins', 'chat_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
