"""hashed password type to str

Revision ID: b3146996541a
Revises: 95392888d827
Create Date: 2026-04-02 15:05:59.605817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3146996541a'
down_revision: Union[str, Sequence[str], None] = '95392888d827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels_admins', 'bot_hashed_password',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels_admins', 'bot_hashed_password',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    # ### end Alembic commands ###
