"""indexes adding

Revision ID: f1021e5f43f4
Revises: 531f379b39d0
Create Date: 2026-04-02 16:51:51.427796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1021e5f43f4'
down_revision: Union[str, Sequence[str], None] = '531f379b39d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('availability_check_index', 'bookings', ['room_id', 'check_in', 'check_out'], unique=False)
    op.create_index('by_city_and_rating', 'hotels', ['city', 'rating'], unique=False)
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    op.create_index(op.f('ix_hotels_country'), 'hotels', ['country'], unique=False)
    op.create_index(op.f('ix_hotels_rating'), 'hotels', ['rating'], unique=False)
    op.drop_constraint(op.f('hotels_admins_hotel_id_key'), 'hotels_admins', type_='unique')
    op.create_index(op.f('ix_hotels_admins_hotel_id'), 'hotels_admins', ['hotel_id'], unique=True)
    op.create_index('by_hotel and price', 'rooms', ['hotel_id', 'price_per_night'], unique=False)
    op.create_index(op.f('ix_rooms_category'), 'rooms', ['category'], unique=False)
    op.create_index(op.f('ix_rooms_hotel_id'), 'rooms', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_rooms_price_per_night'), 'rooms', ['price_per_night'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_price_per_night'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_hotel_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_category'), table_name='rooms')
    op.drop_index('by_hotel and price', table_name='rooms')
    op.drop_index(op.f('ix_hotels_admins_hotel_id'), table_name='hotels_admins')
    op.create_unique_constraint(op.f('hotels_admins_hotel_id_key'), 'hotels_admins', ['hotel_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_hotels_rating'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_country'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_index('by_city_and_rating', table_name='hotels')
    op.drop_index('availability_check_index', table_name='bookings')
    # ### end Alembic commands ###
